### ISSUE TITLE
Introduce a lightbox

### ISSUE THREAD

**Issue by nmalcolm** [mybb/mybb.com#10]
A lightbox should be introduced to help improve browsing through the website. The screenshots are cropped and scaled down so it would improve the user experience.

**Comment by Kaeden** [comment]
Most of the screenshots are still too scaled down to show any additional details even if we use a lightbox (tour screenies for instance).

**Comment by pkill37** [comment]
Which images are we talking about? The feature tour images? I guess users may want to zoom in on those, though I am tempted to just link directly to the full images and avoid the work of implementing a lightbox as well as the extra HTTP requests.

However I would not add a lightbox for the images on the homepage, or generally any hero/jumbotron/banner. That's just marketing stuff, the user doesn't really need to zoom in on it.

**Comment by Kaeden** [comment]
There are no full images for the tour, they already are sized down.

**Comment by pkill37** [comment]
So add full size images.

**Comment by Kaeden** [comment]
If we're to add full images, then we should probably add the lightbox as well, it's still going to be some work replacing them.

**Comment by nmalcolm** [comment]
The idea is to have full size images, scale them down with HTML/CSS, and upon clicking a lightbox appears with the full image.

**Comment by Kaeden** [comment]
It's a pitty I deleted the full size screens from my PC when I replaced the tour images. Now we have to redo them all over again.

@justinsoltesz If I update jquery to the latest version (needed for the lightbox), it will break website functionality? Or should I use a separate header for the tour?

**Comment by nmalcolm** [comment]
@Kaeden No need to update jQuery. I used http://fancyapps.com/fancybox/ which works fine.

The first three pages of the tour have been updated.

**Comment by Stefan-MyBB** [comment]
Though keeping jQuery up-to-date isn't the worst idea. ;)

**Comment by Kaeden** [comment]
I thought of using the same one I used for the mods site... but if this one works too :-)

**Comment by pkill37** [comment]
This has been fully implemented, right?

**Comment by Kaeden** [comment]
Yes, I think so.
