### ISSUE TITLE
mods.php

### ISSUE THREAD

**Issue by ghost** [mybb/mybb.com#102]
Hi,

I was wondering if it would be possible if the team could share the mods.php file from https://community.mybb.com/mods.php please?

Thanks,
Casper

**Comment by AndreRl** [comment]
Keep these type of questions to the forum, where they belong.

**Comment by ghost** [comment]
@AndreRl sorry, I do have the question posted in the forum, but hadn't received any reply yet, when I came across this repository for the mybb.com site I thought this might be a better place to ask.

**Comment by WildcardSearch** [comment]
GitHub is for bug/issue reports, suggested features, etc.

**Comment by euantorano** [comment]
Hi, the mods site is a custom plugin developed solely for the MyBB community forum. We don’t have any plans to open source it, as the plugin is written in such a way that it wouldn’t work on most boards (eg: settings are hard coded, some paths are hard coded to work with our servers, etc.). 

We will be rewriting the mods site for 1.9/1.10 as there’s a plan to overhaul the plugin system in 1.10 and some changes will be needed for the 1.9 theme system. The plan is that this new version will be open source and will be one of our first official MyBB team plugins.
