### ISSUE TITLE
Numbering of feature sub-pages

### ISSUE THREAD

**Issue by pkill37** [mybb/mybb.com#11]
Before we deploy the website, could we remove the numbering in the URLs of the sub-pages under [Features](https://mybb.github.io/mybb.com/features/)?

I am talking about this:

https://mybb.github.io/mybb.com/features/01-ease-of-use/
https://mybb.github.io/mybb.com/features/03-administration/
https://mybb.github.io/mybb.com/features/05-template-and-theme-editor/

The numbers are unnecessary and tacky.

Please? :smile:

**Comment by JordanMussi** [comment]
I think they were added for a reason.... @justinsoltesz? 

I, however, think they are unnecessary also...

**Comment by justinsoltesz** [comment]
The navigation (sidebar, next/previous) in the features section is handled automatically. In order to put them in a certain order, the numbering is necessary.

**Comment by Sama34** [comment]
Can't we add a new field to page for 'preview' & 'next' pages? Unsure if the system works like that, so ignore me if it doesn't.

**Comment by JordanMussi** [comment]
We can remove the numbering in the page name though...

In [_/layouts/feature.html](https://github.com/mybb/mybb.com/blob/gh-pages/_layouts/feature.html):
Replace: `{% assign sorted_pages = site.pages | sort:"name" %}`
With: `{% assign sorted_pages = site.pages | sort:"order" %}`

In the [feature files](https://github.com/mybb/mybb.com/tree/gh-pages/features):
Add to the YAML: `order: 1` (replace with the number previously used in the title...)

I think that should work...

**Comment by justinsoltesz** [comment]
I can look into this later today.

**Comment by justinsoltesz** [comment]
That didn't seem to work. I think the numbers in the URLs will have to stay.

**Comment by JordanMussi** [comment]
Fixed this...

**Comment by JordanMussi** [comment]
Changes didn't fully work so reverted.
The redirects ended up not working in production but did work locally...

**Comment by pkill37** [comment]
Sad :(
