### ISSUE TITLE
Something to think about fo future community improvements

### ISSUE THREAD

**Issue by vintagedaddyo** [mybb/mybb.com#119]
simply curious if there is ever a plan to implement a staff actions complaint function when staff have overstepped so that user may say report such for staff lead review?

Also curious if there will be an adendum to the site documentation that defines if you voluntarily remove your contributions you will be harassed and or treated differently and or punished for such? Also that there will be no option for mediation or resolution, etc, etc, no matter if the staff was wrong and if you return to the site because you got several user requests for missing content that the attempt to complete the request via pm and not public forum posting that you will be permannently banned for being as the ban states "unreasonable"? and say if you attempt to explain why the user request was delayed due to the ban and that you only returned on another acct to let the user know hey I am still trying to provide a completion for your request but cannot without using a new account due to being banned for trying to answer the previous requests thus without such the request is not completed that you then again shall be banned? Me being unreasonable as the ban stated, unreasonable why? because i chose to remove my contributions which is my right as the creator of such and even staff has stated such publicly is the authors right, but when I do so after having plenty of valid reasons to do so and still kindly explain an alternative option for any users still requesting said removed content to just pm me and I will give it to them as my free time allows for thier personal usage but no I do not plan nor desire re-adding such content to the community, I am called unreasonable and banned? Is this method an attempt to force the author to re-add content as that would be a ridiculous approach to accomplishing such, just saying, or is this say simply yet another blatant example of gross abuse of position and title by the offending staff members? watch, get a staff member to scold you on something and then take 20 minutes typing an explanation to help hopefully bring a resolution and watch what happens, it is not read, ignored and you get punished further for simply acting like an adult and trying to provide details and explanations for a peaceful resolution and or to clear up any confusion, misjudgements and or mistakes on either end. I know this happens because I have lived through that hellish experience several times with two specific staff members, not just once but several times before I even finally decided ya know what forget this and began considering full removal of  contributions. I even fairly came back and gave it all another chance and re-added contributions on a new account and gave the comm the benefit of the doubt and again the very same nonsense happened a few months after such thus prompting me to be done with it and such wasting my valuable time and energy and personally being long beyond tired of the negative toxic drama of the entire ordeal, but still even after that I still was kind enough to be like hey folks are asking for this removed contribution or that so lemme give them a less frustating option for myself  and suggest that they could aquire such removed contributions in a way for me that removes the ability to be continually harasssed or punished by certain staff members by suggesting the pm request contributions for personal usage and yet again I am still called unreasonable for such kindness and punished for such? Laughable! Also without providing any means for any user to counter the staff moderation with say an explanation, a request for a higher up on the chain of command to review or repeal such, how is this a viable option as without such you can get alot of staff power trips and abuses if the users cannot appeal? The community is nothing without the members, contributors and contributions nor is a software anything without the users that use it so why is there a lack of aknowledgement that hey if we as a community lose users in droves and they all keep saying they left for a similar reason, Ie: staff behaviors, then it isn't just the user that loses out but also the community, the staff and the software all loses out collectively and if such a trend is seen to be happening then why not as a community figure out how to stop causing users/contributors to lose the love for the community and product and leave. Honestly I have been watching for a long time now and watched tons of valued members and contributors bail on mybb over the years sadly, and the majority explain that it is not the product that made them leave but on the contrary the behaviors of the newer generation staff, so that is a huge issue that really has needed to be adressed and corrected for a long time and I am not the only one that has pointed this obvious fact out. But somehow after pointing out these issues none of this is considered unreasonable behavior on the staff end? I am only asking this as I had after what has it been now something like 15, 16+ years or whatever it has been and hundreds+ contributions (imagine all the hours of time spent to provide hundreds+ of contributions entails not to mention all the time providing for help and support all free of charge for many many years and the kindness and patience it takes to dedicate so much time to such only to be disrespected over and over as honestly that is something I think the staff is forgetting when they start walking all over long time contributors) only came back to answer a request and get banned for doing so thus then only returned to explain the delay and still try to answer the request as the request was still open, none of these current staff choices are reasonable nor make sense and something really needs to be done about this, as a disabled person I really have tried to explain this over and over to no avail ( expressing such is much more difficult than say a non disabled person may realize, though based on past noticing of causes you support I am sure you catch my point on such ) and point out how this really needs to be adressed, corrected and changed for the better  and that is saying something when members being involved for say over 10 or 15 years are bailing the community in droves over this very type of issue, can we get Chris to talk about this and let him make the changes so that we can get back to the old community and the old way where this sort of stuff is not happening as clearly the newer generation of staff are really not handling things correctly? Again just saying, ben you and tom and chris and a few others in my experiences usually are the reasonable ones hence why I was like wow, you should really logically ponder this subject. Also on a humour note, nowhere in history has censoring and muzzling a celt worked out the way the abuser of such had planned, on the contrary it tends to piss celts off like nothing else, especially if we over and over calmly take the time out of ou schedules to explain time and time again with lengthly informative and fact based explanations already only to watch them be ignored and deleted, that is a huge disrespect, haha, thus simply mentioned as food for thought and as one living in scotland I think you might see the humour in such food for thought, lol, also would be amusing if I get the free time next time when I am back in ireland and scotland to swing by and discuss this in person though next trip back is not planned till sometime next year hopefully but it still would be funny to chat on this topic face to face, though ya never know as I was once known to just pop up and knock on doors when folks least expect it, haha. Also as we all know, censoring, changing or deleting history does not change the fact that it happened as it did and those that forget history or do not know history because it has been erased, modified or changed to suit the whims of those in power are doomed to repeat it, again simply some humour based food for thought, haha. Thanks ;)

Also I know it will never happen, but there is a few apologies from certain staff members that are long overdue regardless if it ever happens, just know I know it is owed and would truly be amazed to see them humble themselves just for once just long enough to do the right thing, for once. ;)

* side note: also if this is something that the staff or community say refuses to aknowledge is an existant problem that needs to be corrected, then perhaps any community members that agree such is a problem should start discussing perhaps creating a new mybb community adhering to such proposed changes and bring the old feel and mentalities back to mybb as it was once a really active comm and a truly helpful and positive place to contribute to but that for the most part has not been the case for sadly much too long now as many users have noted both privately and publicly over the last few years. Again just a thought and suggestion and if such is of any interest perhaps folks can contact this temporary email proving_my_point@protonmail.com provided here only for this discussion / topic matter for any to express interest in such or provide suggestions or whatever else along the lines of that particular subject matter.

**Comment by euantorano** [comment]
Hi,

This isn't really the best place for this kind of thing (that would be emailing the `contact -at- mybb.com` email address or posting on community.mybb.com), but I'll answer as best I can.

If you have a problem with a staff member (or multiple thereof), we would usually recommend either emailing the `contact@` email address - this email address is limited to only certain staff members having access; or posting something in the Private Inquiries forum on community.mybb.com.

I'm trying to piece together your actual complaint - if you wish, feel free to correct me or reach out to my email account if you do not want to do so publicly (`euantor -at- mybb.com`).

My understanding is:

- You chose to remove your contributions (plugins, themes, language packs, etc.) from the mods site and the forums
    - This is **totally** within your rights and is not against any of the rules that I am aware of. You should not be punished for making a decision about your own content.
- Your account was banned for some reason? (I need to go back through the moderation logs, forum posts, etc. to confirm this and determine the ban reason if this is the case...)
- After your account was banned did you then create a second account to circumvent the ban? (I may be misunderstanding here - it's not totally clear to me as I don't have time to keep 100% up to date with all community happenings).
    - If so, this is explicitly against the rules we have in place on the community forums.

I would like to piece together what exactly has happened and where you feel we've been wrong or out of place. I can put my hands up and say we're not perfect anything like 100% of the time and we're always trying to grow and improve, but I need to work out the actual circumstances of this complaint to provide clarification.
