### ISSUE TITLE
Change background of #mainFeature on mybb.com

### ISSUE THREAD

**Issue by derKenny** [mybb/mybb.com#15]
Instead of a gradient background you could use the following background color for the ID #mainFeature. # 357BC0 on the homepage. 

Maybe you give it a try?

**Comment by tommykent1210** [comment]
I'm going to close this because I don't think this applies any more. Here is a preview of the proposed change.
![screen shot 2015-06-04 at 10 00 03](https://cloud.githubusercontent.com/assets/1753032/7980571/8f7e8634-0aa0-11e5-8942-0a4cde5050c7.png)
