### ISSUE TITLE
InstantClick issues

### ISSUE THREAD

**Issue by JordanMussi** [mybb/mybb.com#16]
- When returning to the homepage of the website via a link on the page, InstantClick fails to load the slider CSS and/or JS. Thus it leaves the slider as a scroll frame. Therefore the style/js should be included on every page...
- The following should be used to for Google Analytics (see http://instantclick.io/scripts):

``` js
InstantClick.on('change', function() {
  ga('send', 'pageview', location.pathname + location.search);
});
```

**Comment by Ben-MyBB** [comment]
@Eric-Jackson @justinsoltesz Could we fix this for the new release?
