### ISSUE TITLE
hgroup removed from HTML5 specification

### ISSUE THREAD

**Issue by pkill37** [mybb/mybb.com#2]
The hgroup element was removed from the HTML5 specification many months ago. The spec offers advice on how to markup subheadings.

http://www.w3.org/html/wg/drafts/html/master/common-idioms.html#sub-head

Looking at the code we just have to remove the hgroup and replace the last heading with a paragraph.

**Comment by justinsoltesz** [comment]
It looks like the best way to handle this would be to replace hgroup elements with header elements whenever there is both a heading and a subtitle. Subtitles within h2 elements would be changed to paragraph elements.

**Comment by pkill37** [comment]
Yes, that's what the spec now recommends.

**Comment by justinsoltesz** [comment]
Okay, I'm wrapping up the changes now and they'll be committed shortly.

**Comment by pkill37** [comment]
I think you're missing the surrounding `<header>` in some places? Specifically:
- _layouts/default.html
- _layouts/feature.html
- index.html
- features/index.html
- download/index.html

Or am I missing something?

**Comment by justinsoltesz** [comment]
Actually, now that you've pointed it out, the `<section id="mainFeature">` in those places should be the `<header>` for the `<article>` element on those pages. I'll take a look at those places again and see what I can do.
