### ISSUE TITLE
Customize everything area is outdated

### ISSUE THREAD

**Issue by ghost** [mybb/mybb.com#65]
Customize everything area is outdated, since HARAJUJU website shut down. I had bring this into notice of the team long time ago but no updation has been done yet. So making an issue of here as advised by @Ben-Conway 

The out dated image: https://github.com/mybb/mybb.com/blob/gh-pages/assets/images/home/customize_small.png

Should be replaced with some new cool website powered by MyBB.

**Comment by katosdev** [comment]
I propose one of Sharee's sites, either:

- http://sharree.com/
- http://storymunch.com/

**Comment by Ben-MyBB** [comment]
StoryMunch seems like a good one to use.

**Comment by andrewjs18** [comment]
storymunch.com isn't a responsive theme.  imho, we should try to use a forum that scales well on all devices.  sharree.com does scale properly.

JMHO..

**Comment by Ben-MyBB** [comment]
Is the site actually linked anywhere on the homepage though? As far as I'm
aware it's just a little screen shot.

**Comment by justinsoltesz** [comment]
This will be addressed with the new website.

In the meantime, it isn't really an issue ... we aren't linking to the sites, we're just showing what is *possible* with MyBB.
