### ISSUE TITLE
Markup contains errors

### ISSUE THREAD

**Issue by nmalcolm** [mybb/mybb.com#8]
See: http://validator.w3.org/check?uri=http%3A%2F%2Fmybb.github.io%2Fmybb-com%2Ffeatures%2F01-ease-of-use%2F&charset=%28detect+automatically%29&doctype=Inline&group=0&user-agent=W3C_Validator%2F1.3+http%3A%2F%2Fvalidator.w3.org%2Fservices

There are some which aren't so important, but the stray tags should be fixed.

**Comment by justinsoltesz** [comment]
Stray tags and the < label > issue are fixed. I'm not really concerned about the remaining < meta > issues.

**Comment by JordanMussi** [comment]
There are still some issues on the homepage. Are they of any concern?

http://validator.w3.org/check?uri=http%3A%2F%2Fmybb.github.io%2Fmybb-com%2F&charset=%28detect+automatically%29&doctype=Inline&group=0&user-agent=W3C_Validator%2F1.3+http%3A%2F%2Fvalidator.w3.org%2Fservices

**Comment by justinsoltesz** [comment]
I had thought those would be out of our control but it looks like I was able to fix them without any issues.

**Comment by JordanMussi** [comment]
Finding more work for you. ;) The social buttons are present in numerous locations and will all need updating (e.g [http://mybb.github.io/mybb-com/download/](http://validator.w3.org/check?uri=http%3A%2F%2Fmybb.github.io%2Fmybb-com%2Fdownload%2F&charset=%28detect+automatically%29&doctype=Inline&group=0&verbose=1&user-agent=W3C_Validator%2F1.3+http%3A%2F%2Fvalidator.w3.org%2Fservices), [http://mybb.github.io/mybb-com/get-involved/](http://validator.w3.org/check?uri=http%3A%2F%2Fmybb.github.io%2Fmybb-com%2Fget-involved%2F&charset=%28detect+automatically%29&doctype=Inline&group=0&verbose=1&user-agent=W3C_Validator%2F1.3+http%3A%2F%2Fvalidator.w3.org%2Fservices))

**Comment by pkill37** [comment]
Might be a good idea to put those in an include or something, so you don't have to update each instance.

And why do we need a copyright meta tag?

**Comment by justinsoltesz** [comment]
That's a good idea.

You're right, we probably don't need the copyright meta tag.

**Comment by nmalcolm** [comment]
I took a look around and found a few more:

http://validator.w3.org/check?uri=http%3A%2F%2Fmybb.github.io%2Fmybb-com%2Fdownload%2Ftranslations%2F&charset=%28detect+automatically%29&doctype=Inline&group=0&user-agent=W3C_Validator%2F1.3+http%3A%2F%2Fvalidator.w3.org%2Fservices

http://validator.w3.org/check?uri=http%3A%2F%2Fmybb.github.io%2Fmybb-com%2Fcontact%2F&charset=%28detect+automatically%29&doctype=Inline&group=0&user-agent=W3C_Validator%2F1.3+http%3A%2F%2Fvalidator.w3.org%2Fservices

http://validator.w3.org/check?uri=http%3A%2F%2Fmybb.github.io%2Fmybb-com%2Fabout%2Fteam%2F&charset=%28detect+automatically%29&doctype=Inline&group=0&user-agent=W3C_Validator%2F1.3+http%3A%2F%2Fvalidator.w3.org%2Fservices

http://validator.w3.org/check?uri=http%3A%2F%2Fmybb.github.io%2Fmybb-com%2Fdownload%2Fmerge-system%2Flicense%2F&charset=%28detect+automatically%29&doctype=Inline&group=0&user-agent=W3C_Validator%2F1.3+http%3A%2F%2Fvalidator.w3.org%2Fservices

There are some which aren't much of a concern but I'll you let decide what's worth fixing @justinsoltesz.
