### ISSUE TITLE
Rename repository to mybb/mybb.com

### ISSUE THREAD

**Issue by pkill37** [mybb/mybb.com#9]
Just nitpicking, but we should rename the repository to mybb/mybb.com. Note the dot. There's no need to replace it with a dash.

It's a common pattern:

https://github.com/yeoman/yeoman.io
https://github.com/gruntjs/gruntjs.com
https://github.com/LaravelIO/laravel.io

**Comment by nmalcolm** [comment]
@Tim-B

**Comment by JordanMussi** [comment]
To be honest I think this one should be mybb/mybb.github.io and the Docs Repository should be mybb/documentation (or similar).

**Comment by pkill37** [comment]
The docs will be renamed to mybb/docs at some point.

But why should the site be renamed to mybb/mybb.github.io?

**Comment by JordanMussi** [comment]
Both ways are fine, but the <username>.github.io is effectivly the user/org's website. But it goes down to personal preference, therefore it's up to you guys, mybb/mybb.com is just as good. :smile:

**Comment by nmalcolm** [comment]
Done.

http://mybb.github.io/mybb.com/
