### ISSUE TITLE
fb

### ISSUE THREAD

**Issue by mayamim425** [mybb/mybb.com#93]
User-CP >> Edit Profile >> Facebook id/nickname >> Type: "><script>alert(/limb0/)</script>
Then visit one of your threads,and voila.

Proofs:
Configuration:http://postimage.org/image/sumvqlro7/
Testing:http://postimage.org/image/57tjltqb9/

-------------------------------Vulnerable Code---------------------------------------
Line 200-216
					$post["iconfacebook"] = '<a href="http://www.facebook.com/' . $post["facebook"] .'" TARGET=_BLANK><img src="'.$mybb->settings['bburl'].'/images/facebook.gif' .'" /></a>';
					} else 
					{
					}
                } else {
					$post["iconfacebook"] = '<a href="http://www.facebook.com/' . $post["facebook"] .'" TARGET=_BLANK><img src="'.$mybb->settings['bburl'].'/images/facebook.gif' .'" /></a>';
				}	
            }

This vulnerable is dedicated to my brothers. <3

**Comment by dvz** [comment]
This seems like a plugin vulnerability on MyBB 1.6 or earlier - if you believe it's still unpatched, try contacting the author.
For information on reporting security issues affecting MyBB, see https://mybb.com/get-involved/security/

Thanks
